### ISSUE TITLE
扫描完成后出现异常

### ISSUE THREAD

**Issue by 0x584A** [0xbug/SQLiScanner#3]
咨询下大表哥～

运行：`$ python3.5 manage.py celery worker --loglevel=info`

```
[2016-09-20 13:40:13,123: ERROR/MainProcess] Task scanner.tasks.update[4569003b-453d-452f-8bea-567ab27a2b4a] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/x/SQLiScanner/scanner/tasks.py", line 64, in update
    self.mail_to, fail_silently=False)
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.5/smtplib.py", line 337, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.5/smtplib.py", line 393, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

---

另外，如果概览中某条记录一直在扫描中，日志显示`undefined`，那么我要终止或清空执行任务，就只能停止脚本，清空`scanner_sqliscantask`表吗？

**Comment by 0xbug** [comment]
@0x584A 邮箱配置了吗，异常的任务暂时可以通过http://host:port/api删除，后续会在界面上添加操作按钮
